config/routes.rb
Rails.application.routes.draw do
  resources :examples
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resque
  require 'resque/server'
  protected_resque = Rack::Auth::Basic.new(Resque::Server.new) do |username, password|
    username == DEVELOPER_EMAIL && password == (DEVELOPER_PASSWORD)
  end
  mount protected_resque, :at => "/resque"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/example.rb
class Example < ApplicationRecord
end

app/models/experiment.rb
# frozen_string_literal: true

# Try ideas here
# rubocop:disable all
class Experiment
  def perform
    print 'performing experiment'
  end
end
# rubocop:enable all

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: %i[ show edit update destroy ]

  # GET /examples or /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1 or /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples or /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to example_url(@example), notice: "Example was successfully created." }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1 or /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to example_url(@example), notice: "Example was successfully updated." }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1 or /examples/1.json
  def destroy
    @example.destroy

    respond_to do |format|
      format.html { redirect_to examples_url, notice: "Example was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def example_params
      params.require(:example).permit(:title, :body, :seed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_example.html.erb
<div id="<%= dom_id example %>">
  <p>
    <strong>Title:</strong>
    <%= example.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= example.body %>
  </p>

  <p>
    <strong>Seed:</strong>
    <%= example.seed %>
  </p>

</div>

app/views/examples/_form.html.erb
<%= form_with(model: example) do |form| %>
  <% if example.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
        <% example.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :seed, style: "display: block" %>
    <%= form.check_box :seed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<h1>Editing example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Show this example", @example %> |
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Examples</h1>

<div id="examples">
  <% @examples.each do |example| %>
    <%= render example %>
    <p>
      <%= link_to "Show this example", example %>
    </p>
  <% end %>
</div>

<%= link_to "New example", new_example_path %>
<div id="hello-vue-mount-point"></div>

app/views/examples/new.html.erb
<h1>New example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @example %>

<div>
  <%= link_to "Edit this example", edit_example_path(@example) %> |
  <%= link_to "Back to examples", examples_path %>

  <%= button_to "Destroy this example", @example, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render '/stylesheets' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
   <%= render "/javascripts" %>
  </head>

  <body>
    <%= render "/flashes" %>
    <%= yield %>
  </body>
</html>